use serde::{Deserialize, Serialize};

use crate::{object::ObjectInitializer, typedata::Type, value::*};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum ByteCode {
    PUSH(StaticValue),
    POP,
    DUP,
    ADD,
    SUB,
    MULT,
    DIV,
    MOD,
    JMPABS(i64),
    JMPREL(i64),
    JMPTO(String),
    EQUALS,
    LESSER,
    GREATER,
    NEGATE,
    EQLESS,
    EQGREAT,
    CAST(Type),
    AND,
    OR,
    XOR,
    JITL(String),
    JITA(i64),
    JITR(i64),
    GETVARLOCAL(String),
    SAVEVARLOCAL(String),
    GETVARGLOBAL(String),
    SAVEVARGLOBAL(String),
    DEFVAR(String),
    DROPVAR(String),
    CALL(String),
    SHOW,
    RET(bool),
    EXIT,
    INSTANCE(Type,usize),
    GETFROMREF,
    SAVETOREF,
}
